export const frameworks = [
  {
    id: 1,
    name: "IEC 62443",
    score: 79,
    weight: 40,
    trend: "+2",
    status: "Adequate",
    priority: "Primary",
  },
  {
    id: 2,
    name: "ISO/IEC 27001",
    score: 71,
    weight: 20,
    trend: "-1",
    status: "Adequate",
    priority: "Secondary",
  },
  {
    id: 3,
    name: "CEA",
    score: 68,
    weight: 15,
    trend: "+3",
    status: "Weak",
    priority: "Secondary",
  },
  {
    id: 4,
    name: "NCIIPC",
    score: 74,
    weight: 15,
    trend: "+1",
    status: "Adequate",
    priority: "Secondary",
  },
  {
    id: 5,
    name: "NIST CSF",
    score: 70,
    weight: 10,
    trend: "-2",
    status: "Adequate",
    priority: "Secondary",
  },
];