import { Evidence } from "./types";

export const evidenceData: Evidence[] = [
  {
    id: "EV-001",
    title: "Authenticator Rotation Log — HMI-09",
    type: "Configuration Export",
    scope: "HMI-09 / Ankleshwar Plant",
    description: "Password rotation configuration export from HMI station.",
    mappedControls: 1,
    owner: "M. Joshi",
    uploadedBy: "Admin",
    uploadedAt: "2026-06-10",
    approval: "Rejected",
    validity: "Not Approved",
    satisfaction: "Missing",
    fileName: "auth_rotation_hmi09.zip",
    fileSize: "3.4 MB",
    version: "v1.0",
    framework: ["IEC 62443"],
    tags: ["Password", "Authentication", "HMI"],
    reviewedOn: "2026-06-15",
  },

  {
    id: "EV-002",
    title: "Backup Verification Log — EWS-04",
    type: "System Log Export",
    scope: "Engineering Workstation",
    description: "Backup verification log for engineering workstation.",
    mappedControls: 1,
    owner: "R. Iyer",
    uploadedBy: "Operator",
    uploadedAt: "2026-06-08",
    approval: "Approved",
    validity: "Expired",
    satisfaction: "Expired",
    fileName: "backup_verification.pdf",
    fileSize: "1.2 MB",
    version: "v2.1",
    framework: ["ISO 27001"],
    tags: ["Backup", "Logs"],
    expiresOn: "2026-06-25",
  },

  {
    id: "EV-003",
    title: "Firewall Rule Export — Zone B-IT",
    type: "Configuration Export",
    scope: "Zone Boundary B-IT",
    description: "Firewall ACL configuration export.",
    mappedControls: 2,
    owner: "A. Mehta",
    uploadedBy: "Security Team",
    uploadedAt: "2026-06-05",
    approval: "Approved",
    validity: "Current",
    satisfaction: "Satisfied-System",
    fileName: "firewall_rules.xml",
    fileSize: "5.8 MB",
    version: "v3.0",
    framework: ["IEC 62443", "NIST CSF"],
    tags: ["Firewall", "ACL", "Network"],
  },

  {
    id: "EV-004",
    title: "Access Control List Export — Historian-02",
    type: "Configuration Export",
    scope: "Historian-02",
    description: "Exported ACL from Historian server.",
    mappedControls: 1,
    owner: "K. Desai",
    uploadedBy: "Admin",
    uploadedAt: "2026-06-18",
    approval: "Under Review",
    validity: "Current",
    satisfaction: "Partially Satisfied",
    fileName: "historian_acl.csv",
    fileSize: "750 KB",
    version: "v1.2",
    framework: ["IEC 62443"],
    tags: ["ACL", "Historian"],
  },

  {
    id: "EV-005",
    title: "Access Review Sign-off — Halol Pharma",
    type: "Review Record",
    scope: "Plant-wide",
    description: "Quarterly user access review approval.",
    mappedControls: 1,
    owner: "S. Verma",
    uploadedBy: "Compliance Team",
    uploadedAt: "2026-06-12",
    approval: "Approved",
    validity: "Current",
    satisfaction: "Satisfied-Manual",
    fileName: "access_review.pdf",
    fileSize: "820 KB",
    version: "v1.0",
    framework: ["ISO 27001"],
    tags: ["Review", "Access"],
  },

  {
    id: "EV-006",
    title: "Antivirus Status Screenshot",
    type: "Screenshot",
    scope: "SCADA Server",
    description: "Monthly antivirus verification screenshot.",
    mappedControls: 1,
    owner: "A. Patel",
    uploadedBy: "SOC",
    uploadedAt: "2026-06-20",
    approval: "Approved",
    validity: "Current",
    satisfaction: "Satisfied-System",
    fileName: "av_status.png",
    fileSize: "2.1 MB",
    version: "v1.0",
    framework: ["NIST CSF"],
    tags: ["Antivirus", "Security"],
  },

  {
    id: "EV-007",
    title: "Network Segmentation Audit",
    type: "Audit Report",
    scope: "Entire OT Network",
    description: "Annual network segmentation audit.",
    mappedControls: 4,
    owner: "P. Shah",
    uploadedBy: "Audit Team",
    uploadedAt: "2026-06-02",
    approval: "Under Review",
    validity: "Expiring Soon",
    satisfaction: "Partially Satisfied",
    fileName: "network_audit.pdf",
    fileSize: "6.4 MB",
    version: "v5.2",
    framework: ["IEC 62443", "NIST CSF"],
    tags: ["Audit", "Network"],
    expiresOn: "2026-07-05",
  },

  {
    id: "EV-008",
    title: "Remote Access Policy",
    type: "Policy Document",
    scope: "Organization",
    description: "Approved remote access security policy.",
    mappedControls: 2,
    owner: "R. Kumar",
    uploadedBy: "Compliance",
    uploadedAt: "2026-05-30",
    approval: "Approved",
    validity: "Current",
    satisfaction: "Satisfied-Manual",
    fileName: "remote_access_policy.pdf",
    fileSize: "1.5 MB",
    version: "v4.0",
    framework: ["ISO 27001", "NIST CSF"],
    tags: ["Policy", "Remote Access"],
  },
];