export interface Asset {
  id: number;
  asset: string;
  subtitle: string;
  plant: string;
  zone: string;
  purdue: string;
  criticality: "Critical" | "High" | "Medium";
  support: "Supported" | "Unsupported";
  exposure: ("user" | "wifi" | "internet" | "vendor")[];
  owner: string;
  controls: string;
  findings: number;
  status: "Active" | "Offline" | "Maintenance";
}

export const assets: Asset[] = [
  {
    id: 1,
    asset: "PLC-114",
    subtitle: "Programmable Logic Controller",
    plant: "Dahej Specialty Chemicals",
    zone: "Zone B / Process Control",
    purdue: "L1",
    criticality: "Critical",
    support: "Supported",
    exposure: ["user", "wifi"],
    owner: "A. Mehta",
    controls: "11/18",
    findings: 2,
    status: "Active",
  },
  {
    id: 2,
    asset: "HMI-09",
    subtitle: "Human Machine Interface",
    plant: "Ankleshwar Pigments Unit",
    zone: "Control Room / Zone A",
    purdue: "L2",
    criticality: "Critical",
    support: "Supported",
    exposure: ["user", "wifi", "internet"],
    owner: "M. Joshi",
    controls: "9/18",
    findings: 3,
    status: "Active",
  },
  {
    id: 3,
    asset: "Historian-02",
    subtitle: "Data Historian",
    plant: "Jamnagar Refinery Aux.",
    zone: "Zone C / Data Layer",
    purdue: "L3",
    criticality: "High",
    support: "Supported",
    exposure: ["user"],
    owner: "K. Desai",
    controls: "12/18",
    findings: 2,
    status: "Maintenance",
  },
  {
    id: 4,
    asset: "Engineering WS-4",
    subtitle: "Engineering Workstation",
    plant: "Vadodara Polymer Works",
    zone: "Zone A / Engineering",
    purdue: "L3",
    criticality: "High",
    support: "Supported",
    exposure: ["wifi", "vendor"],
    owner: "R. Iyer",
    controls: "10/18",
    findings: 4,
    status: "Offline",
  },
  {
    id: 5,
    asset: "Zone Boundary B-IT",
    subtitle: "Firewall",
    plant: "Dahej Specialty Chemicals",
    zone: "Zone B ↔ IT",
    purdue: "L3.5",
    criticality: "Critical",
    support: "Supported",
    exposure: ["wifi"],
    owner: "A. Mehta",
    controls: "6/18",
    findings: 1,
    status: "Active",
  },
  {
    id: 6,
    asset: "Switch-08",
    subtitle: "Network Switch",
    plant: "Halol Assembly Line",
    zone: "Zone C / Networking",
    purdue: "L2",
    criticality: "Medium",
    support: "Unsupported",
    exposure: ["vendor", "wifi"],
    owner: "S. Patel",
    controls: "8/18",
    findings: 3,
    status: "Active",
  },
  {
    id: 7,
    asset: "Firewall-21",
    subtitle: "Zone Boundary Firewall",
    plant: "Ankleshwar Pigments Unit",
    zone: "Zone C / Edge",
    purdue: "L3",
    criticality: "Critical",
    support: "Supported",
    exposure: ["internet", "vendor"],
    owner: "N. Shah",
    controls: "15/18",
    findings: 0,
    status: "Active",
  },
  {
    id: 8,
    asset: "PLC-208",
    subtitle: "Process Controller",
    plant: "Vadodara Polymer Works",
    zone: "Zone B / Process Control",
    purdue: "L1",
    criticality: "High",
    support: "Supported",
    exposure: ["user", "internet"],
    owner: "R. Iyer",
    controls: "13/18",
    findings: 5,
    status: "Maintenance",
  },
  {
    id: 9,
    asset: "HMI-18",
    subtitle: "Operator Interface",
    plant: "Jamnagar Refinery Aux.",
    zone: "Control Room / Zone A",
    purdue: "L2",
    criticality: "Medium",
    support: "Unsupported",
    exposure: ["user", "vendor"],
    owner: "P. Shah",
    controls: "7/18",
    findings: 2,
    status: "Offline",
  },
];
